log.boot.file = "log.log"
log.boot.level = "INFO"

log.code.file = "log.log"
log.code.level = "DEBUG"

log.periferics.file = "periferics.log"
log.periferics.level = "DEBUG"

log.deviceController.file = "deviceController.log"
log.deviceController.level = "DEBUG"
